# Generated by Django 5.1.6 on 2025-03-06 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davomat',
            name='sana',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='familiya',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('topshiriq', models.TextField()),
                ('bajarildi', models.BooleanField(default=False)),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.talaba')),
            ],
        ),
    ]
